version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-bootstrap
    versions:
    - ">= 4.a, < 5"
  - dependency-name: ember-template-lint
    versions:
    - 2.20.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
  - dependency-name: ember-qunit
    versions:
    - 5.1.3
