name: ember-workshop.simplabs.com

sass:
  sass_dir: css

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

title: simplabs
author: simplabs GmbH
description: Ember.js Workshops by simplabs

url: http://simplabs.com
logo: /images/logo@2x.png

twitter:
  username: simplabs
facebook:
  publisher: https://www.facebook.com/simplabs/
