name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - auth
          - component-composition
          - components
          - core-concepts
          - dependencies
          - ember-data
          - example-addon
          - object-model
          - routing
          - services
          - templates
          - web-sockets
          - tomster-player

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn workspace ${{ matrix.workspace }} lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - auth
          - component-composition
          - components
          - core-concepts
          - dependencies
          - ember-data
          - example-addon
          - object-model
          - routing
          - services
          - templates
          - web-sockets
          - tomster-player

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: tests
        run: yarn workspace ${{ matrix.workspace }} test
