name: CI

on:
  push:
    branches:
      - master
      - github-actions
      - tomster-player
    tags:
      - step*
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - auth
          - component-composition
          - components
          - core-concepts
          - dependencies
          - ember-data
          - example-addon
          - routing
          - services
          - templates
          - web-sockets

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
          cache: yarn

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn workspace ${{ matrix.workspace }} lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace:
          - auth
          - component-composition
          - components
          - core-concepts
          - dependencies
          - ember-data
          - example-addon
          - routing
          - services
          - templates
          - web-sockets

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 10.x
          cache: yarn

      - name: install dependencies
        run: yarn install

      - name: tests
        run: yarn workspace ${{ matrix.workspace }} test
