name: CI

on:
  push:
    branches:
      - master
      - github-actions
      - tomster-player
    tags:
      - step*
  pull_request: {}

env:
  PNPM_VERSION: 7.29.3

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workspace:
          - auth
          - component-composition
          - components
          - core-concepts
          - dependencies
          - ember-data
          - example-addon
          - routing
          - services
          - templates
          - web-sockets

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm --filter ${{ matrix.workspace }} lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workspace:
          - auth
          - component-composition
          - components
          - core-concepts
          - dependencies
          - ember-data
          - example-addon
          - routing
          - services
          - templates
          - web-sockets

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: tests
        run: pnpm --filter ${{ matrix.workspace }} test
